### ISSUE TITLE
Car Upgrade

### ISSUE THREAD

**Issue by Adlez** [LordOfDarknessAlexander/Auto_ObsessionsX#13]
Selecting a Car in the Garage and then Upgrade (also from the Garage) takes you to the upgrade screen for a random car that probably isn't what you selected To change which car is loaded you must reload the webpage, and another random car will be selected.
*However, if you select View from the Garage, and then in the vehicle view "Select" the vehicle and move to the upgrade screen, it will be the car you selected in the Vehicle View Screen.

**Comment by vigilance91** [comment]
caused by an outdated api call that never got changed
